### ISSUE TITLE
Losing all translations on opening

### ISSUE THREAD

**Issue by loranger** [christofferok/langly#4]
Hello,

Thank you for this awesome tool, but I met an issue:

I tried to upgrade an exisiting project from the php array translations files to the _new_ json format in order to use Langly. I have a lot of translation keys, but I don't know if it's the source of the problem.

Each time I launch Langly the already translated string a not found and empty. 
I thought one of my strings were corrupting the json file, but even with three translations Langly cannot get the translations back, even if the file is generated by Langly itself

I tried with few strings on the following screencast: http://take.ms/iQ0Ul

What did I miss ?

**Comment by nam-co** [comment]
Hi loranger, I suggest starting with a brand new json just to check if its working, I use it everyday and it works, I tried to cover the php the first time, same as you and it was a nightmare, ended redoing the json file and this gave me the opportunity to clean my lang files, if I remember correctly my error was in a (" or ') even the json tool said it was ok, same as you.

Good luck

**Comment by loranger** [comment]
Thanks for your support @nam-co !

I had a remaining `fr.json.json` which Langly did not like at all.
Now everything is perfectly handled and [my conversion script](https://gist.github.com/loranger/61a1f6b750dc25a9d542b5e44ff36f0f) works like a charm.

It was definitely my fault, sorry for the noise

**Comment by nam-co** [comment]
Thank you for the script, hope everything works
